# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-16 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scheduled_sending",
                    models.DateTimeField(
                        null=True,
                        verbose_name="\u0417\u0430\u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u043e\u0435 \u0432\u0440\u0435\u043c\u044f \u0438 \u0434\u0430\u0442\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f",
                    ),
                ),
                (
                    "is_send",
                    models.BooleanField(
                        default=False,
                        verbose_name="\u041f\u0438\u0441\u044c\u043c\u043e \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e",
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=False,
                        verbose_name="\u041f\u0438\u0441\u044c\u043c\u043e \u043f\u0440\u043e\u0447\u0438\u0442\u0430\u043d\u043e",
                    ),
                ),
            ],
            options={
                "verbose_name": "\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0430 \u043f\u0438\u0441\u0435\u043c",
                "verbose_name_plural": "\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0430 \u043f\u0438\u0441\u0435\u043c",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        verbose_name="\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435",
                    ),
                ),
                ("subject", models.TextField(verbose_name="\u0422\u0435\u043c\u0430")),
                (
                    "message",
                    models.TextField(
                        verbose_name="\u0428\u0430\u0431\u043b\u043e\u043d"
                    ),
                ),
            ],
            options={
                "verbose_name": "\u0428\u0430\u0431\u043b\u043e\u043d \u043f\u0438\u0441\u044c\u043c\u0430",
                "verbose_name_plural": "\u0428\u0430\u0431\u043b\u043e\u043d\u044b \u043f\u0438\u0441\u0435\u043c",
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="\u0418\u043c\u044f"),
                ),
                (
                    "second_name",
                    models.CharField(
                        max_length=100,
                        verbose_name="\u0424\u0430\u043c\u0438\u043b\u0438\u044f",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        verbose_name="\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
            ],
            options={
                "verbose_name": "\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438",
                "verbose_name_plural": "\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u0438 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438",
            },
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="email_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="email_sender.EmailTemplate",
                verbose_name="\u0428\u0430\u0431\u043b\u043e\u043d",
            ),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="email_sender.Subscriber",
                verbose_name="\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a",
            ),
        ),
    ]
